# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ITProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITProject
  # MongoDB Swift Driver (not using any more, delete later)
  # pod 'StitchSDK', '~> 6.0.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Core'

  pod 'SVProgressHUD'

  pod "UPCarouselFlowLayout"
  pod 'SideMenu'
  pod 'EnhancedCircleImageView'
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Zip', '~> 1.1'

end
